version: '3.1'

services:
  api:
    build: backend/
    ports:
      - "5000:5000"
    volumes:
      - './backend/app:/app'
    restart: "on-failure"
    links:
      - elasticsearch:elasticsearch
  frontend:
    build: frontend/
    ports:
      - "8080:8080"
    volumes:
      - './frontend/app:/app'
      - 'node_modules:/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.2.2'
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"

volumes:
  node_modules:
