version: '3.1'

services:
  api:
    build: backend/
    ports:
      - "5000:5000"
    volumes:
      - './backend/app:/app'
  front:
    build: frontend/
    ports:
      - "8080:8080"
    volumes:
      - './frontend/front:/front'
