version: '3.1'

services:
  api:
    build: backend/
    ports:
      - "5000:5000"
    volumes:
      - './backend/app:/app'
  frontend:
    build: frontend/
    ports:
      - "8080:8080"
    volumes:
      - './frontend/app:/app'
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.2.2'
    ports:
    - "9200:9200"
    - "9300:9300"
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"