version: '3.1'

services:
  api:
    depends_on:
      - elasticsearch
    build: backend/
    ports:
      - "5000:5000"
    volumes:
      - './backend/app:/app'
    restart: "${DOCKER_RESTART}"
    links:
      - elasticsearch:elasticsearch
  frontend:
    build: frontend/
    depends_on:
      - api
    ports:
      - "8080:8080"
    volumes:
      - './frontend/app:/app'
      - 'node_modules:/app/node_modules'
    restart: "${DOCKER_RESTART}"
    environment:
      - CHOKIDAR_USEPOLLING=true
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.2.2'
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
  test_runner:
    links:
      - elasticsearch:elasticsearch
      - frontend:frontend
      - api:api
    depends_on:
      - frontend
    image: willwill/wait-for-it
    entrypoint: "bash -c '/wait-for-it.sh --timeout=60 elasticsearch:9200 && /wait-for-it.sh --timeout=15 api:5000 && /wait-for-it.sh --timeout=15 frontend:8080 && exit 0'"

volumes:
  node_modules:
