version: '3.1'

services:
  api:
    build: backend/
    ports:
      - "5000:5000"
    volumes:
      - './backend/app:/app'
  frontend:
    build: frontend/
    ports:
      - "8080:8080"
    volumes:
      - './frontend/app:/app'
      - 'node_modules:/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  node_modules: